// <auto-generated />
using System;
using APDB_PJATK_CW4_s30115.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APDB_PJATK_CW4_s30115.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525191751_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("APDB_PJATK_CW4_s30115.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "0000000001",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "i7-13700K",
                            Name = "i7-13700K"
                        },
                        new
                        {
                            Code = "0000000002",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 2,
                            Description = "RX 7900 XTX",
                            Name = "RX 7900 XTX"
                        },
                        new
                        {
                            Code = "0000000003",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 3,
                            Description = "Vengeance DDR5 32GB",
                            Name = "Vengeance DDR5 32GB"
                        },
                        new
                        {
                            Code = "0000000004",
                            ComponentManufacturersId = 4,
                            ComponentTypesId = 4,
                            Description = "980 Pro 1TB",
                            Name = "980 Pro 1TB"
                        },
                        new
                        {
                            Code = "0000000005",
                            ComponentManufacturersId = 5,
                            ComponentTypesId = 5,
                            Description = "ROG Strix B650-A",
                            Name = "ROG Strix B650-A"
                        });
                });

            modelBuilder.Entity("APDB_PJATK_CW4_s30115.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "Intel",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1969, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "AMD"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "Corsair",
                            FoundationDate = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Corsair"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "Samsung",
                            FoundationDate = new DateTime(1969, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Samsung"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "ASUS",
                            FoundationDate = new DateTime(1989, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "ASUS"
                        });
                });

            modelBuilder.Entity("APDB_PJATK_CW4_s30115.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "GPU"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SSD",
                            Name = "SSD"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "MB",
                            Name = "MB"
                        });
                });

            modelBuilder.Entity("APDB_PJATK_CW4_s30115.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warranty")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PC-Workstation-01",
                            Stock = 5,
                            Warranty = 24,
                            Weight = 10.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "PC-Workstation-02",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 8.5
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "PC-Server-01",
                            Stock = 3,
                            Warranty = 36,
                            Weight = 15.0
                        });
                });

            modelBuilder.Entity("APDB_PJATK_CW4_s30115.Models.PCComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "0000000001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "0000000002",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "0000000003",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "0000000005",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "0000000001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "0000000003",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "0000000004",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "0000000002",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "0000000003",
                            Amount = 4
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "0000000004",
                            Amount = 2
                        });
                });

            modelBuilder.Entity("APDB_PJATK_CW4_s30115.Models.Component", b =>
                {
                    b.HasOne("APDB_PJATK_CW4_s30115.Models.ComponentManufacturer", "Manufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APDB_PJATK_CW4_s30115.Models.ComponentType", "Type")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("APDB_PJATK_CW4_s30115.Models.PCComponent", b =>
                {
                    b.HasOne("APDB_PJATK_CW4_s30115.Models.Component", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APDB_PJATK_CW4_s30115.Models.PC", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("APDB_PJATK_CW4_s30115.Models.Component", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("APDB_PJATK_CW4_s30115.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("APDB_PJATK_CW4_s30115.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("APDB_PJATK_CW4_s30115.Models.PC", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
